language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-ui
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/nuc-node:7.2.1

install:
  - git fetch --tags
  - if [ -f "package.json" ]; then
    	npm i;
    else
      npm i git://github.com/resin-io/versionist.git#agile versionist-plugins;
    fi

before_install:
  - curl -O -L https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz
  - tar xvfz rocker_linux_amd64.tar.gz
  - git config --global user.name "Agile CI Bot" && git config --global user.email "bot@http://agile-iot.eu/"
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Rockerfile ; fi

script:
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      export DOCKER_TAG=$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      git checkout -b origin/${TRAVIS_PULL_REQUEST_BRANCH};
      git merge origin/master;
      versionist -d;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      export DOCKER_TAG=$TRAVIS_TAG;
    else
      export DOCKER_TAG=$TRAVIS_BRANCH;
    fi
  - if [[ -n ${DOCKER_TAG} ]]; then
      ./rocker build -var Repo=$DOCKER_IMAGE -var Version=$DOCKER_TAG;
    fi

after_success:
  - if [[ -n ${DOCKER_TAG} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $DOCKER_IMAGE:$DOCKER_TAG;
    fi
  - if [ "$DOCKER_TAG" == "master" ]; then
      docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE;
      docker push $DOCKER_IMAGE;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -z ${TRAVIS_TAG} ]]; then
      git checkout master;
      git remote set-url origin https://$GH_TOKEN@github.com/agile-iot/$COMPONENT.git;
      versionist;
    fi
