language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-ui
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
      VERSIONIST=true
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/intel-nuc-node:7.8.0-20170506

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)
  - cache_load
  - bootstrap
  - echo "Tagging the build with tag - $DOCKER_TAG"

script:
  - travis_wait 30 docker_build_if_needed
  - cache_save

after_success:
  - docker_push_if_needed
  - versionist_if_needed
