// Fetching device lists
export const DEVICELIST_FETCH = 'DEVICELIST_FETCH'
export const DEVICELIST_FETCH_SUCCESS = 'DEVICELIST_FETCH_SUCCESS'
export const DEVICELIST_FETCH_FAILURE = 'DEVICELIST_FETCH_FAILURE'

// per device actions on device
export const ADD_DEVICE = 'ADD_DEVICE'
export const STAR_DEVICE = 'STAR_DEVICE'
export const DELETE_DEVICE = 'DELETE_DEVICE'

// settings
export const DISCOVERY = 'DISCOVERY'
export const DISCOVERY_SUCCESS = 'DISCOVERY_SUCCESS'
export const DISCOVERY_FAILURE = 'DISCOVERY_FAILURE'
