// Fetching device lists
export const DEVICELIST_FETCH_REQUESTED = 'DEVICELIST_FETCH_REQUESTED'
export const DEVICELIST_FETCH_SUCCEEDED = 'DEVICELIST_FETCH_SUCCEEDED'
export const DEVICELIST_FETCH_FAILED = 'DEVICELIST_FETCH_FAILED'

// per device actions on device
export const DEVICE_FETCH_REQUESTED = 'DEVICE_FETCH_REQUESTED'
export const DEVICE_FETCH_SUCCEEDED = 'DEVICE_FETCH_SUCCEEDED'
export const DEVICE_FETCH_FAILED = 'DEVICE_FETCH_FAILED'

// settings
export const SETTINGS_DRAWER_TOGGLE = 'SETTINGS_DRAWER_TOGGLE'

export const SETTINGS_DISCOVERY_REQUESTED = 'SETTINGS_DISCOVERY_REQUESTED'
export const SETTINGS_DISCOVERY_SUCCEEDED = 'SETTINGS_DISCOVERY_SUCCEEDED'
export const SETTINGS_DISCOVERY_FAILED = 'SETTINGS_DISCOVERY_FAILED'
