// router
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

// Fetching device lists
export const DEVICELIST_FETCH = 'DEVICELIST_FETCH'
export const DEVICELIST_FETCH_SUCCEEDED = 'DEVICELIST_FETCH_SUCCEEDED'
export const DEVICELIST_FETCH_FAILED = 'DEVICELIST_FETCH_FAILED'

// per device actions on device
export const DEVICE_REGISTER = 'DEVICE_REGISTER'
export const DEVICE_REGISTER_SUCCEEDED = 'DEVICE_REGISTER_SUCCEEDED'
export const DEVICE_REGISTER_FAILED = 'DEVICE_REGISTER_FAILED'

export const DEVICE_FETCH = 'DEVICE_FETCH'
export const DEVICE_FETCH_SUCCEEDED = 'DEVICE_FETCH_SUCCEEDED'
export const DEVICE_FETCH_FAILED = 'DEVICE_FETCH_FAILED'

export const DEVICE_DELETE = 'DEVICE_DELETE'
export const DEVICE_DELETE_SUCCEEDED = 'DEVICE_DELETE_SUCCEEDED'
export const DEVICE_DELETE_FAILED = 'DEVICE_DELETE_FAILED'

// settings
export const SETTINGS_DRAWER_TOGGLE = 'SETTINGS_DRAWER_TOGGLE'

export const SETTINGS_DISCOVERY = 'SETTINGS_DISCOVERY'
export const SETTINGS_DISCOVERY_SUCCEEDED = 'SETTINGS_DISCOVERY_SUCCEEDED'
export const SETTINGS_DISCOVERY_FAILED = 'SETTINGS_DISCOVERY_FAILED'
